version: '3'

services:
  api:
    image: upluse10/ictsc-score-server:api
    env_file: .env
    build:
      context: api/
    depends_on:
      - db
      - redis
    ports:
      # environment: では指定できないので.envで指定する必要がある
      - "${EXPOSE_API_PORT}:3000"
    stdin_open: true
    tty: true
    volumes:
      - "./api:/usr/src/app"
    command: |
      dockerize -wait tcp://redis:6379 -timeout 100s
      dockerize -wait tcp://db:3306 -timeout 100s
      rake server
  ui:
    image: upluse10/ictsc-score-server:ui
    env_file: .env
    build:
      context: ui/
    depends_on:
      - api
      - plasma
    ports:
      - "${EXPOSE_UI_PORT}:80"

  redis:
    image: redis:4.0.11-alpine
    env_file: .env
    ports:
      - "${EXPOSE_REDIS_PORT}:6379"

  db:
    image: mariadb:10.3
    env_file: .env
    ports:
      - "${EXPOSE_DB_PORT}:3306"
    # デバック用に永続化したい場合はコメントアウト
    # volumes:
    #   - "./tmp/db:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  plasma:
    image: openfresh/plasma:latest
    env_file: .env
    depends_on:
      - redis
    ports:
      - "${EXPOSE_PLASMA}:8080"
      # - 50051:50051

  yamllint:
    image: upluse10/ictsc-score-server:yamllint
    build:
      context: yamllint/
    volumes:
      - "./:/usr/src/app"
    command: yamllint -c /usr/src/app/.yamllint /usr/src/app
