version: '3'

services:
  api_old:
    image: upluse10/ictsc-score-server:api-old
    env_file: .env
    build:
      context: api/
    depends_on:
      - db_old
      - redis_old
    ports:
      - "8910:3000"
    stdin_open: true
    tty: true
    volumes:
      - "./api:/usr/src/app"
    command: >
      sh -c "
      dockerize -wait tcp://redis_old:6379 -timeout 100s &&
      dockerize -wait tcp://db_old:3306 -timeout 100s &&
      rake db:setup db:seed_fu &&
      rackup -o 0.0.0.0 -p 3000
      "

  ui_old:
    image: upluse10/ictsc-score-server:ui-old
    env_file: .env
    build:
      context: ui/
    depends_on:
      - plasma_old
    ports:
      - "8911:80"
    volumes:
      - "./ui/h2o:/etc/h2o"

  redis_old:
    image: redis:4.0.11-alpine
    env_file: .env
    ports:
      - "8912:6379"

  db_old:
    image: mariadb:10.3
    env_file: .env
    ports:
      - "8913:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  plasma_old:
    image: openfresh/plasma:latest
    env_file: .env
    depends_on:
      - redis_old
    ports:
      - "8914:8080"
