version: '3'

services:
  web:
    build:
      context: .
    image: ictsc-score-server:dev
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
    - "./:/usr/src/app"
    stdin_open: true
    tty: true
  db:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - "./tmp/db:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    env_file: .env
