version: '3'

services:
  ui:
    build:
      context: ui2
    image: ictsc-score-server:ui
    ports:
      - "3001:80"
    restart: always
    links:
      - api
      - plasma
  api:
    build:
      context: .
    image: ictsc-score-server:api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    stdin_open: true
    tty: true
    volumes:
      - "./:/usr/src/app"
  db:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - "./tmp/db:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  plasma:
    image: openfresh/plasma:latest
    ports:
      - 3002:8080
      # - 50051:50051
    depends_on:
      - redis
    env_file: .env
    environment:
      PLASMA_DEBUG: "true"
      PLASMA_SUBSCRIBER_TYPE: redis
      PLASMA_SUBSCRIBER_REDIS_OVER_MAX_RETRY_BEHAVIOR: alive
      PLASMA_SUBSCRIBER_REDIS_MAX_RETRY: 5
      PLASMA_SUBSCRIBER_REDIS_TIMEOUT: 1s
      PLASMA_SUBSCRIBER_REDIS_RETRY_INTERBAL: 5s
      PLASMA_ORIGIN: "*"
  redis:
    image: redis:3.2.9-alpine
  yamllint:
    image: upluse10/ictsc-score-server:yamllint
    build:
      context: yamllint/
    volumes:
      - "./:/usr/src/app"
    command: yamllint -c /usr/src/app/.yamllint /usr/src/app
