version: '3'

services:
  api:
    image: upluse10/ictsc-score-server:api
    env_file: .env
    build:
      context: api2/
    depends_on:
      - db
      - redis
    ports: ['8900:3000']
    stdin_open: true
    tty: true
    volumes:
      - './api2:/usr/src/app'
    command: sh -c '
      if [ -f "tmp/pids/server.pid" ]; then
        rm tmp/pids/server.pid;
      fi

      dockerize -wait tcp://redis:6379 -timeout 100s
      dockerize -wait tcp://db:5432 -timeout 100s
      bundle exec rails server puma -b 0.0.0.0
      '

  # ui:
  #   image: upluse10/ictsc-score-server:ui
  #   env_file: .env
  #   build:
  #     context: ui/
  #   depends_on:
  #     - plasma
  #   ports:
  #     - "8901:80"
  #   volumes:
  #     - "./ui/h2o:/etc/h2o"

  db:
    image: postgres:11.3-alpine
    env_file: .env
    ports: ['8902:5432']

  redis:
    image: redis:5.0.4-alpine
    env_file: .env
    ports: ['8903:6379']

    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  yamllint:
    image: upluse10/ictsc-score-server:yamllint
    build:
      context: yamllint/
    volumes:
      - './:/usr/src/app'
    command: yamllint -c /usr/src/app/.yamllint /usr/src/app
