---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.16.30.11
    path: "/opt/nfs/contest_api"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: api
spec:
  template:
    metadata:
      labels:
        ictsc2018-score: api
    spec:
      containers:
        - image: upluse10/ictsc-score-server:api
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8900
              name: api
          envFrom:
            - configMapRef:
                name: api-env
          volumeMounts:
            - name: api-volume
              mountPath: /usr/src/app/uploads
      restartPolicy: Always
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: api-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
data:
  TZ: "Asia/Tokyo"
  RACK_ENV: "production"
  RAILS_ENV: "production"
  MYSQL_HOST: "db"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_DATABASE: "ictsc_score_server"
  MYSQL_PASSWORD: "PASSWORD"
  MYSQL_ROOT_PASSWORD: "PASSWORD"
  API_SESSION_USE_REDIS: "y"
  API_SESSION_COOKIE_KEY: "ictsc_score_server"
  API_SESSION_COOKIE_SECRET: "SECRET"
  API_SESSION_REDIS_SERVER: "redis://redis:6379/0"
  API_CONTEST_REDIS_REALTIME_NOTIFICATION_CHANNEL: "realtime_notification"
  PLASMA_SUBSCRIBER_REDIS_ADDR: "redis:6379"
  PLASMA_SUBSCRIBER_REDIS_CHANNELS: "realtime_notification"
  REDIS_URL: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ictsc2018-score: api
  name: api
spec:
  ports:
    - name: api
      port: 8900
      targetPort: 8900
  selector:
    ictsc2018-score: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - contest.icttoracon.net
      secretName: contest
  rules:
    - host: contest.icttoracon.net
      http:
        paths:
          - path: /api
            backend:
              serviceName: api
              servicePort: 8900
