---
- key: competition_time_day1_start_at
  value_type: date
  value: '2012-09-03T10:00:00+09:00'
- key: competition_time_day1_end_at
  value_type: date
  value: '2112-09-03T18:00:00+09:00'
- key: competition_time_day2_start_at
  value_type: date
  value: '2112-09-03T10:00:00+09:00'
- key: competition_time_day2_end_at
  value_type: date
  value: '2112-09-03T18:00:00+09:00'
- key: competition_stop
  value_type: boolean
  value: 'false'
- key: problem_open_all_at
  value_type: date
  value: '2112-09-03T11:00:00+09:00'
- key: grading_delay_sec
  value_type: integer
  value: '30'
- key: scoreboard_hide_at
  value_type: date
  value: '2112-09-03T12:00:00+09:00'
- key: scoreboard_top
  value_type: integer
  value: '3'
- key: scoreboard_display_top_team
  value_type: boolean
  value: 'true'
- key: scoreboard_display_top_score
  value_type: boolean
  value: 'true'
- key: scoreboard_display_above_team
  value_type: boolean
  value: 'false'
- key: scoreboard_display_above_score
  value_type: boolean
  value: 'true'
