Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: 'space'
  EnforcedStyleForEmptyBraces: 'no_space'
  SpaceBeforeBlockParameters: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false

MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200
Metrics/LineLength:
  Enabled: false
# etrics/BlockLength:

Style/IfUnlessModifier:
  Enabled: false
  # MaxLineLength: 120

Naming/HeredocDelimiterNaming:
  Enabled: false
Style/Documentation:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false

CaseIndentation:
  IndentOneStep: false
  EnforcedStyle: 'case'
Layout/BlockAlignment:
  EnforcedStyleAlignWith: 'start_of_block'
Layout/IndentHash:
  EnforcedStyle: 'consistent'
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

# その内外すかも
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Documentation:
#   Enabled: false
# Style/ClassAndModuleChildren:
#   Enabled: false
# Style/CommentedKeyword:
#   Enabled: false
# Style/RedundantBegin:
#   Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/**/*_spec.rb'
    - 'spec/**/*_helper.rb'
    - 'spec/support/**/*'
    - 'tmp/**/*'
